version: 2.1

orbs:
  node: circleci/node@5.1.0
  macos: circleci/macos@2.3.6

jobs:
  ios_test:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.large.gen1
    steps:
      - checkout
      - macos/preboot-simulator:
          device: iPhone 13
          version: "15.5"
      - node/install-packages
      - run:
          name: Start Appium Server
          command: npx appium
          background: true
      - run:
          name: Run tests
          command: npm run ios.app

workflows:
  appium_test:
    jobs:
      - ios_test
